server:
  port: 8083
spring:
  application:
    name: house-service
  # datasource druid
  datasource:
    druid:
      url: jdbc:mysql://192.168.11.214:3306/spring_cloud_eamon
      username: springcloud
      password: springcloud
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化连接数
      initial-size: 10
      # 最小连接数
      min-idle: 5
      # 最大连接数
      max-active: 50
      # 获取连接时最大的等待时间  单位毫秒
      max-wait: 60000
      # Destroy线程会检测连接的间隔时间
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000
      # 检测连接是否有效的sql
      validation-query: SELECT 1 FROM DUAL
      # 检测连接是否有效
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效
      test-on-return: false
      # 定时输出统计日志的世界，毫秒
      time-between-log-stats-millis: 300000
      # 是否缓存preparedStatement，也就是PSCache
      pool-prepared-statements: true
      # Statement缓存大小
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j
      # 连接属性
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000


eureka:
  client:
    serviceUrl:
      defaultZone: http://eamon:eamon@localhost:8761/eureka/, http://eamon:eamon@localhost:8762/eureka/
    # 开启健康检查 需要引入actuator依赖
    helthcheck:
      enabled: true
  instance:
    #改变服务注册的 instance ID形式为 服务名：主机名：端口
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instalce_id:${server.port}}
    # 点击实力id时进行ip跳转
    preferIpAddress: true
    # 点击注册中心的服务地址跳转到对应服务的api文档
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
    # 默认30秒 开发环境改为 5秒  表示客户端发送心跳给注册中心server的频率
    lease-renewal-interval-in-seconds: 5
    # 默认90秒 表示eureka server至上一次收到 client的心跳之后，等待下一次心跳的超时时间，如果在这个时间内没有收到下一次心跳，就移除该Instance
    lease-expiration-duration-in-seconds: 5
